import React from "react";
import {
    View,
    Text,
    StyleSheet,
    ScrollView,
    TouchableOpacity,
    SafeAreaView,
    Platform,
    StatusBar,
} from "react-native";
import { useRouter } from "expo-router";
import { Ionicons } from "@expo/vector-icons";

export default function TermsOfService() {
    const router = useRouter();

    return (
        <SafeAreaView style={styles.container}>
            <StatusBar barStyle="dark-content" />
            
            {/* Header */}
            <View style={styles.header}>
                <TouchableOpacity 
                    style={styles.backButton} 
                    onPress={() => router.back()}
                >
                    <Ionicons name="arrow-back" size={24} color="#1A1A1A" />
                </TouchableOpacity>
                <Text style={styles.headerTitle}>Terms of Service</Text>
                <View style={styles.headerSpacer} />
            </View>

            <ScrollView 
                style={styles.scrollView}
                contentContainerStyle={styles.scrollContent}
                showsVerticalScrollIndicator={false}
            >
                {/* Title */}
                <View style={styles.titleSection}>
                    <Text style={styles.mainTitle}>Planera</Text>
                    <Text style={styles.subtitle}>Terms of Use</Text>
                    <Text style={styles.lastUpdated}>Last updated: December 18, 2024</Text>
                </View>

                {/* Section 1 */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>1. Introduction</Text>
                    <Text style={styles.sectionText}>
                        Welcome to Planera ("we", "our", "us"). Planera is an AI-powered travel planning application that generates personalized travel itineraries based on user inputs.
                    </Text>
                    <Text style={styles.sectionText}>
                        By accessing or using Planera, you agree to be bound by these Terms of Use. If you do not agree, please do not use the app.
                    </Text>
                </View>

                {/* Section 2 */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>2. Nature of the Service</Text>
                    <Text style={styles.sectionText}>
                        Planera provides AI-generated travel plans and recommendations for informational and inspiration purposes only.
                    </Text>
                    <View style={styles.warningBox}>
                        <Text style={styles.warningText}>❗ Planera is not a travel agency, tour operator, or booking platform.</Text>
                        <Text style={styles.warningText}>❗ We do not sell, organize, or operate travel services.</Text>
                        <Text style={styles.warningText}>❗ All bookings (transportation, accommodation, activities) are made directly by the user with third-party providers.</Text>
                    </View>
                </View>

                {/* Section 3 */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>3. AI-Generated Content Disclaimer</Text>
                    <Text style={styles.sectionText}>
                        Travel plans generated by Planera are created using artificial intelligence and may contain inaccuracies, outdated information, or incomplete suggestions.
                    </Text>
                    <Text style={styles.sectionText}>
                        Prices, availability, routes, schedules, and regulations may change at any time.
                    </Text>
                    <Text style={styles.sectionText}>
                        Users are responsible for verifying all details before making any booking or travel decision.
                    </Text>
                    <Text style={styles.sectionTextBold}>
                        Planera assumes no liability for errors, omissions, or changes related to AI-generated content.
                    </Text>
                </View>

                {/* Section 4 */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>4. User Responsibilities</Text>
                    <Text style={styles.sectionText}>You agree to:</Text>
                    <View style={styles.bulletList}>
                        <Text style={styles.bulletItem}>• Provide accurate and truthful information</Text>
                        <Text style={styles.bulletItem}>• Use the app for lawful purposes only</Text>
                        <Text style={styles.bulletItem}>• Verify all travel details independently</Text>
                        <Text style={styles.bulletItem}>• Comply with local laws, visa requirements, and travel regulations</Text>
                    </View>
                    <Text style={styles.sectionTextBold}>
                        You acknowledge that all travel decisions are made at your own discretion and risk.
                    </Text>
                </View>

                {/* Section 5 */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>5. Subscriptions & Payments</Text>
                    <Text style={styles.sectionText}>
                        Planera may offer free and paid subscription plans.
                    </Text>
                    <View style={styles.bulletList}>
                        <Text style={styles.bulletItem}>• Payments are processed through Apple App Store or Google Play</Text>
                        <Text style={styles.bulletItem}>• Subscription pricing, billing cycles, and renewal terms are shown before purchase</Text>
                        <Text style={styles.bulletItem}>• Subscriptions automatically renew unless canceled through your store account</Text>
                        <Text style={styles.bulletItem}>• Refunds are subject to Apple / Google policies</Text>
                    </View>
                </View>

                {/* Section 6 */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>6. Intellectual Property</Text>
                    <Text style={styles.sectionText}>
                        All content, design, branding, AI outputs, and software related to Planera are the intellectual property of Planera or its licensors.
                    </Text>
                    <Text style={styles.sectionText}>
                        You may not copy, modify, distribute, or resell any part of the service without written permission.
                    </Text>
                </View>

                {/* Section 7 */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>7. Limitation of Liability</Text>
                    <Text style={styles.sectionText}>
                        To the maximum extent permitted by law, Planera shall not be liable for:
                    </Text>
                    <View style={styles.bulletList}>
                        <Text style={styles.bulletItem}>• Travel disruptions</Text>
                        <Text style={styles.bulletItem}>• Booking issues</Text>
                        <Text style={styles.bulletItem}>• Financial losses</Text>
                        <Text style={styles.bulletItem}>• Missed connections</Text>
                        <Text style={styles.bulletItem}>• Third-party service failures</Text>
                        <Text style={styles.bulletItem}>• Personal injury or damages</Text>
                    </View>
                    <Text style={styles.sectionTextBold}>
                        Use of the app is at your own risk.
                    </Text>
                </View>

                {/* Section 8 */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>8. Termination</Text>
                    <Text style={styles.sectionText}>
                        We reserve the right to suspend or terminate access to Planera if these Terms are violated.
                    </Text>
                </View>

                {/* Section 9 */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>9. Governing Law</Text>
                    <Text style={styles.sectionText}>
                        These Terms are governed by the laws of the European Union and applicable national legislation.
                    </Text>
                </View>

                {/* Section 10 */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>10. Contact</Text>
                    <Text style={styles.sectionText}>
                        For questions regarding these Terms, contact:
                    </Text>
                    <View style={styles.contactBox}>
                        <Ionicons name="mail-outline" size={20} color="#D4A853" />
                        <Text style={styles.contactEmail}>support@planera.app</Text>
                    </View>
                </View>

                {/* Footer spacing */}
                <View style={styles.footer} />
            </ScrollView>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FBF7F0",
        paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(0,0,0,0.05)",
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#FFFFFF",
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#1A1A1A",
    },
    headerSpacer: {
        width: 40,
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 24,
    },
    titleSection: {
        alignItems: "center",
        marginBottom: 32,
    },
    mainTitle: {
        fontSize: 32,
        fontWeight: "800",
        color: "#1A1A1A",
        marginBottom: 4,
    },
    subtitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#666666",
        marginBottom: 8,
    },
    lastUpdated: {
        fontSize: 14,
        color: "#999999",
    },
    section: {
        marginBottom: 28,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "700",
        color: "#1A1A1A",
        marginBottom: 12,
    },
    sectionText: {
        fontSize: 15,
        lineHeight: 24,
        color: "#444444",
        marginBottom: 12,
    },
    sectionTextBold: {
        fontSize: 15,
        lineHeight: 24,
        color: "#1A1A1A",
        fontWeight: "600",
        marginTop: 8,
    },
    warningBox: {
        backgroundColor: "#FFF8E7",
        borderRadius: 12,
        padding: 16,
        borderLeftWidth: 4,
        borderLeftColor: "#D4A853",
    },
    warningText: {
        fontSize: 14,
        lineHeight: 22,
        color: "#1A1A1A",
        marginBottom: 8,
    },
    bulletList: {
        marginLeft: 8,
        marginTop: 8,
    },
    bulletItem: {
        fontSize: 15,
        lineHeight: 26,
        color: "#444444",
    },
    contactBox: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#FFFFFF",
        borderRadius: 12,
        padding: 16,
        marginTop: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
    },
    contactEmail: {
        fontSize: 16,
        fontWeight: "600",
        color: "#D4A853",
        marginLeft: 12,
    },
    footer: {
        height: 40,
    },
});
